server:
  port: 8000
dubbo:
  scan:
    base-packages: com.springcloud.dubbo_provider_web.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services:
spring:
  application:
    name: dubbo-spring-cloud-provider-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true